/* PipPose — Pip mascot with different poses (neutral, correct, almost)
   Uses the SoT Lock B SVG exports from Figma. */

interface PipPoseProps {
  pose?: 'neutral' | 'correct' | 'almost';
  className?: string;
}

export default function PipPose({ pose = 'neutral', className }: PipPoseProps) {
  if (pose === 'correct') {
    return (
      <svg
        className={className}
        width="56"
        height="56"
        viewBox="0 0 56 56"
        fill="none"
        xmlns="http://www.w3.org/2000/svg"
      >
        <g id="Art">
          <rect
            id="stem"
            x="26.25"
            y="8.4"
            width="3.5"
            height="23.8"
            rx="1.75"
            fill="#3f7a2e"
          />
          <ellipse
            id="leaf-left"
            cx="23.1"
            cy="9.1"
            rx="11.2"
            ry="6.65"
            fill="#6FBF5E"
            transform="rotate(-36 28 12.6)"
          />
          <ellipse
            id="leaf-right"
            cx="32.9"
            cy="9.1"
            rx="11.2"
            ry="6.65"
            fill="#4D9E3F"
            transform="rotate(36 28 12.6)"
          />
          <circle
            id="junction"
            cx="28"
            cy="12.6"
            r="2.24"
            fill="#3f7a2e"
          />
          <circle
            id="head"
            cx="28"
            cy="37.1"
            r="12.6"
            fill="#6FBF5E"
          />
          <circle
            id="head-highlight"
            cx="28"
            cy="37.1"
            r="12.6"
            fill="#ffffff"
            opacity="0.06"
          />
          <circle
            id="eye-left"
            cx="23.8"
            cy="34.65"
            r="1.89"
            fill="#2f3b24"
          />
          <circle
            id="eye-right"
            cx="32.2"
            cy="34.65"
            r="1.89"
            fill="#2f3b24"
          />
          <path
            id="grin"
            d="M20.65 36.75 q7.35 10.85 14.7 0"
            stroke="#2f3b24"
            strokeWidth="2.1"
            fill="none"
            strokeLinecap="round"
          />
          <circle
            id="cheek-left"
            cx="19.95"
            cy="39.2"
            r="1.82"
            fill="#ffffff"
            opacity="0.28"
          />
          <circle
            id="cheek-right"
            cx="36.05"
            cy="39.2"
            r="1.82"
            fill="#ffffff"
            opacity="0.28"
          />
        </g>
      </svg>
    );
  }

  if (pose === 'almost') {
    return (
      <svg
        className={className}
        width="56"
        height="56"
        viewBox="0 0 56 56"
        fill="none"
        xmlns="http://www.w3.org/2000/svg"
      >
        <g id="Art">
          <rect
            id="stem"
            x="26.25"
            y="13.3"
            width="3.5"
            height="19.6"
            rx="1.75"
            fill="#3f7a2e"
          />
          <ellipse
            id="leaf-left"
            cx="21"
            cy="14"
            rx="11"
            ry="6.2"
            fill="#6FBF5E"
            transform="rotate(-45 28 17)"
          />
          <ellipse
            id="leaf-right"
            cx="35"
            cy="14"
            rx="11"
            ry="6.2"
            fill="#4D9E3F"
            transform="rotate(40 28 16)"
          />
          <circle
            id="junction"
            cx="28"
            cy="16.8"
            r="2.4"
            fill="#3f7a2e"
          />
          <circle
            id="head"
            cx="28"
            cy="37.1"
            r="12.6"
            fill="#6FBF5E"
          />
          <circle
            id="head-highlight"
            cx="28"
            cy="37.1"
            r="12.6"
            fill="#ffffff"
            opacity="0.06"
          />
          <ellipse
            id="eye-left"
            cx="23.8"
            cy="34.8"
            rx="1.8"
            ry="2.4"
            fill="#2f3b24"
          />
          <ellipse
            id="eye-right"
            cx="32.2"
            cy="34.6"
            rx="1.8"
            ry="2.4"
            fill="#2f3b24"
          />
          <path
            id="smile"
            d="M22.5 38.5 q5.5 6 11 0"
            stroke="#2f3b24"
            strokeWidth="2.1"
            fill="none"
            strokeLinecap="round"
          />
          <circle
            id="cheek-left"
            cx="19.95"
            cy="39.2"
            r="1.82"
            fill="#ffffff"
            opacity="0.28"
          />
          <circle
            id="cheek-right"
            cx="36.05"
            cy="39.2"
            r="1.82"
            fill="#ffffff"
            opacity="0.28"
          />
        </g>
      </svg>
    );
  }

  return (
    <svg
      className={className}
      width="56"
      height="56"
      viewBox="0 0 56 56"
      fill="none"
      xmlns="http://www.w3.org/2000/svg"
    >
      <g id="Art">
        <rect
          id="stem"
          x="26.25"
          y="13.3"
          width="3.5"
          height="19.6"
          rx="1.75"
          fill="#3f7a2e"
        />
        <ellipse
          id="leaf-left"
          cx="23"
          cy="15"
          rx="10.5"
          ry="6"
          fill="#6FBF5E"
          transform="rotate(-35 28 16.8)"
        />
        <ellipse
          id="leaf-right"
          cx="33"
          cy="15"
          rx="10.5"
          ry="6"
          fill="#4D9E3F"
          transform="rotate(35 28 16.8)"
        />
        <circle
          id="junction"
          cx="28"
          cy="16.8"
          r="2.4"
          fill="#3f7a2e"
        />
        <circle
          id="head"
          cx="28"
          cy="37.1"
          r="12.6"
          fill="#6FBF5E"
        />
        <circle
          id="head-highlight"
          cx="28"
          cy="37.1"
          r="12.6"
          fill="#ffffff"
          opacity="0.06"
        />
        <ellipse
          id="eye-left"
          cx="23.8"
          cy="35"
          rx="1.8"
          ry="2.3"
          fill="#2f3b24"
        />
        <ellipse
          id="eye-right"
          cx="32.2"
          cy="35"
          rx="1.8"
          ry="2.3"
          fill="#2f3b24"
        />
        <path
          id="smile"
          d="M22 38 q6 7 12 0"
          stroke="#2f3b24"
          strokeWidth="2.1"
          fill="none"
          strokeLinecap="round"
        />
        <circle
          id="cheek-left"
          cx="19.95"
          cy="39.2"
          r="1.82"
          fill="#ffffff"
          opacity="0.28"
        />
        <circle
          id="cheek-right"
          cx="36.05"
          cy="39.2"
          r="1.82"
          fill="#ffffff"
          opacity="0.28"
        />
      </g>
    </svg>
  );
}
